version: '3'
services:
  weatherService:
    restart: always
    image: weatherservice:v0.0.1
    container_name: "weatherservice"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms128m-Xmx128m
      - APP_WEATHER_RESOURCE=all
    networks:
      - network
networks:
  network: